version: 2
updates:
  - package-ecosystem: npm
    directory: /router
    schedule:
      interval: daily
    assignees:
      - prasek
  - package-ecosystem: npm
    directory: /subgraphs/products
    schedule:
      interval: daily
    assignees:
      - prasek
  - package-ecosystem: npm
    directory: /subgraphs/users
    schedule:
      interval: daily
    assignees:
      - prasek
  - package-ecosystem: npm
    directory: /subgraphs/inventory
    schedule:
      interval: daily
    assignees:
      - prasek
