apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-router
  labels:
    app: graphql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
      - name: gateway
        image: prasek/supergraph-demo:latest
        env:
        - name: GATEWAY_PORT
          value: "3999"
        - name: GATEWAY_ENV
          value: "Prod"
        - name: GATEWAY_SUPERGRAPH_SDL
          value: "supergraph.graphql"
        ports:
        - containerPort: 3999
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-service
spec:
  selector:
    app: graphql
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 3999
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graphql-ingress
  annotations:
    kubernetes.io/ingress.class: ambassador
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: graphql-service
            port: 
              number: 4001
