name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 7,19 * * *'

jobs:
  test-docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "PATH=$PATH:$HOME/.rover/bin" >> ${GITHUB_ENV}
      - name: Start stack
        run: |
          make supergraph
          docker-compose up -d
          sleep 3
          docker-compose logs
      - name: smoke test
        run: .scripts/smoke.sh 4000
      - name: Stop stack
        run: docker-compose down
