name: CI
on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 7,19 * * *'

jobs:
  test-docker:
    name: CI
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "PATH=$PATH:$HOME/.rover/bin" >> ${GITHUB_ENV}
      - name: make supergraph
        run: |
          make supergraph
      - name: docker-compose up -d
        run: |
          docker-compose up -d
          sleep 3
          docker-compose logs
      - name: smoke test
        run: .scripts/smoke.sh 4000
      - name: docker-compose down
        run: docker-compose down
