name: Subgraph Check
on:
  pull_request:
    branches: [ main ]

jobs:
  subgraph-check:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        rover-version: ["latest"]
        subgraph: ["orders", "products", "reviews", "customers", "inventory", "locations"]
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      GRAPH_REF: supergraph-preview@current

    name: ${{ matrix.subgraph }}
    steps:
      - uses: actions/checkout@v2
      - name: install rover
        env:
          ROVER_VERSION: ${{ matrix.rover-version }}
        run: |
          curl -sSL https://rover.apollo.dev/nix/$ROVER_VERSION | sh
          echo "PATH=$PATH:$HOME/.rover/bin" >> ${GITHUB_ENV}
      - name: check
        if: env.APOLLO_KEY != 0
        run: rover subgraph check $GRAPH_REF --schema subgraphs/${{ matrix.subgraph }}.graphql --name ${{ matrix.subgraph }}
      - name: skip check
        if: env.APOLLO_KEY == 0
        run: echo skipping subgraph check due to public repo fork PR not having secrets access.
