name: Supergraph Build Webhook

on:
  schedule:
    - cron: '*/5 * * * *'
  repository_dispatch:
    types: [studio-build-webhook]
jobs:
  supergraph-build-webhook:
    runs-on: ubuntu-18.04
    concurrency:
      group: global
      cancel-in-progress: true
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      GRAPH_REF: supergraph-preview@current
      PR_BRANCH: studio-build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: install rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "PATH=$PATH:$HOME/.rover/bin" >> ${GITHUB_ENV}
      -
        id: pre-check
        run: |
          SHA=$(shasum supergraph.graphql | awk '{print $1}')
          echo "::set-output name=sha::$SHA"
          echo "::set-output name=sha-short::$(git rev-parse --short $SHA)"
      -
        name: supergraph fetch
        run: rover supergraph fetch $GRAPH_REF > supergraph.graphql
      -
        id: check
        run: |
          echo "::set-output name=result::$(git diff --name-only | grep -E 'supergraph.graphql')"
          SHA=$(shasum supergraph.graphql | awk '{print $1}')
          echo "::set-output name=sha::$SHA"
          echo "::set-output name=sha-short::$(git rev-parse --short $SHA)"
      -
        name: validate
        if: steps.check.outputs.result == 'supergraph.graphql'
        env:
          RESULT: ${{ steps.check.outputs.result }}
          SHA: ${{ steps.check.outputs.sha }}
          SHA_SHORT: ${{ steps.check.outputs.sha-short }}
        run: |
          echo "RESULT: $RESULT"
          echo "SHA: $SHA"
          echo "SHA_SHORT: $SHA_SHORT"
          DIFF=$(git diff supergraph.graphql)
          echo "DIFF<<EOF" >> $GITHUB_ENV
          echo "$DIFF" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "-----------------------"
          echo "supergraph.graphql"
          echo "-----------------------"
          echo "$DIFF"
      -
        name: create pull request
        id: cpr
        if: steps.check.outputs.result == 'supergraph.graphql'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          committer: Supergraph Demo Bot <prasek+bot@gmail.com>
          author: Supergraph Demo Bot <prasek+bot@gmail.com>
          commit-message: Bump supergraph schema from ${{ steps.pre-check.outputs.sha-short }} to ${{ steps.check.outputs.sha-short }}
          title:  Bump supergraph schema from ${{ steps.pre-check.outputs.sha-short }} to ${{ steps.check.outputs.sha-short }}
          body: |
            Bump supergraph schema from ${{ steps.pre-check.outputs.sha-short }} to ${{ steps.check.outputs.sha-short }} for ${{ env.GRAPH_REF }}:
            * Old: SHA1 ${{ steps.pre-check.outputs.sha }} ( ${{ steps.pre-check.outputs.sha-short }} )
            * New: SHA1 ${{ steps.check.outputs.sha }} ( ${{ steps.check.outputs.sha-short }} )

            <details>
            <summary>Changes</summary>

            ```diff
            ${{ env.DIFF }}

            ```

            </details>
          branch: ${{ env.PR_BRANCH }}
          base: main
          delete-branch: true
      -
       name: enable pull request automerge
       if: |
         steps.check.outputs.result == 'supergraph.graphql' &&
         steps.cpr.outputs.pull-request-operation == 'created'
       uses: peter-evans/enable-pull-request-automerge@v1
       with:
         token: ${{ secrets.PAT }}
         pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
         merge-method: squash
      - name: Check output
        if: |
          steps.check.outputs.result == 'supergraph.graphql' &&
          steps.cpr.outputs.pull-request-operation == 'created'
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      - name: No changes detected
        if: |
          steps.check.outputs.result == 0 ||
          steps.cpr.outputs.pull-request-operation != 'created'
        run: |
          echo "No changes to '$GRAPH_REF' detected"
