name: Supergraph Gateway Docker Push

on:
  push:
    branches:
      - 'main'
    paths:
      - "Dockerfile"
      - "package.json"
      - "index.js"
      - "supergraph.graphql"
      - "k8s/*"
      - ".scripts/*"

jobs:
  gateway-docker:
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: prasek/supergraph-demo:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  k8s:
    runs-on: ubuntu-18.04
    needs: gateway-docker
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: update kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x ./kind
          mkdir -p $HOME/.kind/bin
          mv ./kind $HOME/.kind/bin/kind
          echo "PATH=$HOME/.kind/bin:$PATH" >> ${GITHUB_ENV}
      -
        name: test-k8s
        run: .scripts/ci-k8s.sh
